print ("Write X")
x =  int(input ())
print ("Write Y")
y = int(input ())

print ("x+y= ", x+y)
print ("x-y= ", x-y)
print ("x*y= ", x*y)
print ("x/y= ", x/y)
print ("x//y= ", x//y)
print ("x%y= ", x%y)
print ("x**y= ", x**y)
